language: node_js
node_js:
  - 'lts/*'

jobs:
  include:
    - stage: Checks
      # name: Check Doc links
      # - script:
      #   - gem install awesome_bot
      #   - awesome_bot *.md --allow-redirect --white-list travis-ci,packagephobia.now

      # name: Check Typing
      script: npm run check-typing

      # name: Check Formatting
      script: npm run check-formatting


      # name: Lint
      script: npm run lint

      # name: Check Prepublish
      # script: npm run prepublishOnly

    # - stage: Tests
    #   if: branch = master
    #   - script: npm run test:coverage & npm run coveralls
    #     name: Run Unit Tests, generate coverage and publish to coveralls

    #   - script: npm run test:mutation-report"
    #     name: Run Mutation Tests and publish reports

    # - stage: Tests
    #   if: NOT branch = master
    #   - script: npm run test
    #     name: Run Unit Tests

    #   - script: npm run test:mutation
    #     name: Run Mutation Tests

    - stage: Publish
      name: 'Publish to gh-pages'
      script: echo "Some console message"
