language: node_js
node_js:
  - 'lts/*'

jobs:
  include:
    - name: Check Doc links
      script:
        - gem install awesome_bot
        - awesome_bot *.md --allow-redirect --white-list travis-ci,packagephobia.now

    - name: Check Formatting
      script: npm run check-formatting

    - name: Check Typing
      script: npm run check-typing

    - name: Lint
      script: npm run lint

    - name: Run test and generate coverage
      if: (branch = master)
      script: npm run test:coverage & npm run coveralls

    - name: Run test
      if: (NOT branch = master)
      script: npm run test

    - name: Run and publish Mutation tests
      if: (branch = master)
      script: npm run test:mutation-report"

    - name: Check Prepublish
      script: npm run prepublishOnly

  after_success:
    - echo "Some console message"
