language: node_js
node_js:
  - 'lts/*'

jobs:
  include:
    - stage: Checks
      script:
        # - name: Check Doc links
        - gem install awesome_bot
        - awesome_bot *.md --allow-redirect --white-list travis-ci,packagephobia.now

        # - name: Check Formatting
        - npm run check-formatting

        # - name: Check Typing
        - npm run check-typing

        # - name: Lint
        - npm run lint

        # - name: Check Prepublish
        - npm run prepublishOnly

    - stage: Tests
      if: branch = master
      script:
        # - name: Run Unit Tests, generate coverage and publish to coveralls
        - npm run test:coverage & npm run coveralls
        # - name: Run Mutation Tests and publish reports
        - npm run test:mutation-report"

    - stage: Tests
      if: NOT branch = master
      script:
        # - name: Run Unit Tests
        - npm run test
        # - name: Run Mutation Tests
        - npm run test:mutation

    - stage: Publish
      name: 'Publish to gh-pages'
      script:
        - echo "Some console message"
